//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.17 at 04:30:35 PM IST 
//


package com.bonton.utility.hotelbeds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hotel"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="rooms"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="room" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="rates"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="rate"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="cancellationPolicies"&gt;
 *                                                             &lt;complexType&gt;
 *                                                               &lt;complexContent&gt;
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                   &lt;sequence&gt;
 *                                                                     &lt;element name="cancellationPolicy"&gt;
 *                                                                       &lt;complexType&gt;
 *                                                                         &lt;simpleContent&gt;
 *                                                                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                                                             &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                                                                             &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                                                                             &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                                                                           &lt;/extension&gt;
 *                                                                         &lt;/simpleContent&gt;
 *                                                                       &lt;/complexType&gt;
 *                                                                     &lt;/element&gt;
 *                                                                   &lt;/sequence&gt;
 *                                                                 &lt;/restriction&gt;
 *                                                               &lt;/complexContent&gt;
 *                                                             &lt;/complexType&gt;
 *                                                           &lt;/element&gt;
 *                                                         &lt;/sequence&gt;
 *                                                         &lt;attribute name="rateKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="rateClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="rateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="rateComment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="packaging" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="boardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="boardName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="rooms" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                                         &lt;attribute name="adults" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                                         &lt;attribute name="children" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                                         &lt;attribute name="net" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="checkIn" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                 &lt;attribute name="checkOut" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="destinationCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="destinationName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="zoneName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="zoneCode" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                 &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="totalNet" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="error" type="{http://www.hotelbeds.com/schemas/messages}ErrorRS"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hotel",
    "error"
})
@XmlRootElement(name = "checkRateRS")
public class CheckRateRS {

    @XmlElement(required = true)
    protected CheckRateRS.Hotel hotel;
    @XmlElement(required = true)
    protected ErrorRS error;

    /**
     * Gets the value of the hotel property.
     * 
     * @return
     *     possible object is
     *     {@link CheckRateRS.Hotel }
     *     
     */
    public CheckRateRS.Hotel getHotel() {
        return hotel;
    }

    /**
     * Sets the value of the hotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckRateRS.Hotel }
     *     
     */
    public void setHotel(CheckRateRS.Hotel value) {
        this.hotel = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorRS }
     *     
     */
    public ErrorRS getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorRS }
     *     
     */
    public void setError(ErrorRS value) {
        this.error = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="rooms"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="room" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="rates"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="rate"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="cancellationPolicies"&gt;
     *                                                   &lt;complexType&gt;
     *                                                     &lt;complexContent&gt;
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                         &lt;sequence&gt;
     *                                                           &lt;element name="cancellationPolicy"&gt;
     *                                                             &lt;complexType&gt;
     *                                                               &lt;simpleContent&gt;
     *                                                                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                                                                   &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *                                                                   &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *                                                                   &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *                                                                 &lt;/extension&gt;
     *                                                               &lt;/simpleContent&gt;
     *                                                             &lt;/complexType&gt;
     *                                                           &lt;/element&gt;
     *                                                         &lt;/sequence&gt;
     *                                                       &lt;/restriction&gt;
     *                                                     &lt;/complexContent&gt;
     *                                                   &lt;/complexType&gt;
     *                                                 &lt;/element&gt;
     *                                               &lt;/sequence&gt;
     *                                               &lt;attribute name="rateKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="rateClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="rateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="rateComment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="packaging" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="boardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="boardName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="rooms" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                                               &lt;attribute name="adults" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                                               &lt;attribute name="children" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                                               &lt;attribute name="net" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="checkIn" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *       &lt;attribute name="checkOut" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="destinationCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="destinationName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="zoneName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="zoneCode" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *       &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="totalNet" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rooms"
    })
    public static class Hotel {

        @XmlElement(required = true)
        protected CheckRateRS.Hotel.Rooms rooms;
        @XmlAttribute(name = "checkIn")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar checkIn;
        @XmlAttribute(name = "checkOut")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar checkOut;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "code")
        protected String code;
        @XmlAttribute(name = "description")
        protected String description;
        @XmlAttribute(name = "categoryCode")
        protected String categoryCode;
        @XmlAttribute(name = "categoryName")
        protected String categoryName;
        @XmlAttribute(name = "destinationCode")
        protected String destinationCode;
        @XmlAttribute(name = "destinationName")
        protected String destinationName;
        @XmlAttribute(name = "zoneName")
        protected String zoneName;
        @XmlAttribute(name = "zoneCode")
        protected Integer zoneCode;
        @XmlAttribute(name = "latitude")
        protected Float latitude;
        @XmlAttribute(name = "longitude")
        protected Float longitude;
        @XmlAttribute(name = "currency")
        protected String currency;
        @XmlAttribute(name = "totalNet")
        protected String totalNet;

        /**
         * Gets the value of the rooms property.
         * 
         * @return
         *     possible object is
         *     {@link CheckRateRS.Hotel.Rooms }
         *     
         */
        public CheckRateRS.Hotel.Rooms getRooms() {
            return rooms;
        }

        /**
         * Sets the value of the rooms property.
         * 
         * @param value
         *     allowed object is
         *     {@link CheckRateRS.Hotel.Rooms }
         *     
         */
        public void setRooms(CheckRateRS.Hotel.Rooms value) {
            this.rooms = value;
        }

        /**
         * Gets the value of the checkIn property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCheckIn() {
            return checkIn;
        }

        /**
         * Sets the value of the checkIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCheckIn(XMLGregorianCalendar value) {
            this.checkIn = value;
        }

        /**
         * Gets the value of the checkOut property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCheckOut() {
            return checkOut;
        }

        /**
         * Sets the value of the checkOut property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCheckOut(XMLGregorianCalendar value) {
            this.checkOut = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the categoryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryCode() {
            return categoryCode;
        }

        /**
         * Sets the value of the categoryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryCode(String value) {
            this.categoryCode = value;
        }

        /**
         * Gets the value of the categoryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryName() {
            return categoryName;
        }

        /**
         * Sets the value of the categoryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryName(String value) {
            this.categoryName = value;
        }

        /**
         * Gets the value of the destinationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationCode() {
            return destinationCode;
        }

        /**
         * Sets the value of the destinationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationCode(String value) {
            this.destinationCode = value;
        }

        /**
         * Gets the value of the destinationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationName() {
            return destinationName;
        }

        /**
         * Sets the value of the destinationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationName(String value) {
            this.destinationName = value;
        }

        /**
         * Gets the value of the zoneName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZoneName() {
            return zoneName;
        }

        /**
         * Sets the value of the zoneName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZoneName(String value) {
            this.zoneName = value;
        }

        /**
         * Gets the value of the zoneCode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getZoneCode() {
            return zoneCode;
        }

        /**
         * Sets the value of the zoneCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setZoneCode(Integer value) {
            this.zoneCode = value;
        }

        /**
         * Gets the value of the latitude property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setLatitude(Float value) {
            this.latitude = value;
        }

        /**
         * Gets the value of the longitude property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setLongitude(Float value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the totalNet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalNet() {
            return totalNet;
        }

        /**
         * Sets the value of the totalNet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalNet(String value) {
            this.totalNet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="room" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="rates"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="rate"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="cancellationPolicies"&gt;
         *                                         &lt;complexType&gt;
         *                                           &lt;complexContent&gt;
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                               &lt;sequence&gt;
         *                                                 &lt;element name="cancellationPolicy"&gt;
         *                                                   &lt;complexType&gt;
         *                                                     &lt;simpleContent&gt;
         *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                                                         &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         *                                                         &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
         *                                                         &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         *                                                       &lt;/extension&gt;
         *                                                     &lt;/simpleContent&gt;
         *                                                   &lt;/complexType&gt;
         *                                                 &lt;/element&gt;
         *                                               &lt;/sequence&gt;
         *                                             &lt;/restriction&gt;
         *                                           &lt;/complexContent&gt;
         *                                         &lt;/complexType&gt;
         *                                       &lt;/element&gt;
         *                                     &lt;/sequence&gt;
         *                                     &lt;attribute name="rateKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="rateClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="rateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="rateComment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="packaging" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="boardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="boardName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="rooms" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                                     &lt;attribute name="adults" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                                     &lt;attribute name="children" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                                     &lt;attribute name="net" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "room"
        })
        public static class Rooms {

            protected List<CheckRateRS.Hotel.Rooms.Room> room;

            /**
             * Gets the value of the room property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the room property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRoom().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CheckRateRS.Hotel.Rooms.Room }
             * 
             * 
             */
            public List<CheckRateRS.Hotel.Rooms.Room> getRoom() {
                if (room == null) {
                    room = new ArrayList<CheckRateRS.Hotel.Rooms.Room>();
                }
                return this.room;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="rates"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="rate"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="cancellationPolicies"&gt;
             *                               &lt;complexType&gt;
             *                                 &lt;complexContent&gt;
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                     &lt;sequence&gt;
             *                                       &lt;element name="cancellationPolicy"&gt;
             *                                         &lt;complexType&gt;
             *                                           &lt;simpleContent&gt;
             *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *                                               &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
             *                                               &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
             *                                               &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
             *                                             &lt;/extension&gt;
             *                                           &lt;/simpleContent&gt;
             *                                         &lt;/complexType&gt;
             *                                       &lt;/element&gt;
             *                                     &lt;/sequence&gt;
             *                                   &lt;/restriction&gt;
             *                                 &lt;/complexContent&gt;
             *                               &lt;/complexType&gt;
             *                             &lt;/element&gt;
             *                           &lt;/sequence&gt;
             *                           &lt;attribute name="rateKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="rateClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="rateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="rateComment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="packaging" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="boardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="boardName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="rooms" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *                           &lt;attribute name="adults" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *                           &lt;attribute name="children" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *                           &lt;attribute name="net" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "rates"
            })
            public static class Room {

                @XmlElement(required = true)
                protected CheckRateRS.Hotel.Rooms.Room.Rates rates;
                @XmlAttribute(name = "code")
                protected String code;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the rates property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CheckRateRS.Hotel.Rooms.Room.Rates }
                 *     
                 */
                public CheckRateRS.Hotel.Rooms.Room.Rates getRates() {
                    return rates;
                }

                /**
                 * Sets the value of the rates property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CheckRateRS.Hotel.Rooms.Room.Rates }
                 *     
                 */
                public void setRates(CheckRateRS.Hotel.Rooms.Room.Rates value) {
                    this.rates = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="rate"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="cancellationPolicies"&gt;
                 *                     &lt;complexType&gt;
                 *                       &lt;complexContent&gt;
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                           &lt;sequence&gt;
                 *                             &lt;element name="cancellationPolicy"&gt;
                 *                               &lt;complexType&gt;
                 *                                 &lt;simpleContent&gt;
                 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                 *                                     &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                 *                                     &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
                 *                                     &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                 *                                   &lt;/extension&gt;
                 *                                 &lt;/simpleContent&gt;
                 *                               &lt;/complexType&gt;
                 *                             &lt;/element&gt;
                 *                           &lt;/sequence&gt;
                 *                         &lt;/restriction&gt;
                 *                       &lt;/complexContent&gt;
                 *                     &lt;/complexType&gt;
                 *                   &lt;/element&gt;
                 *                 &lt;/sequence&gt;
                 *                 &lt;attribute name="rateKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="rateClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="rateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="rateComment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="packaging" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="boardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="boardName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="rooms" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                 *                 &lt;attribute name="adults" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                 *                 &lt;attribute name="children" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                 *                 &lt;attribute name="net" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "rate"
                })
                public static class Rates {

                    @XmlElement(required = true)
                    protected CheckRateRS.Hotel.Rooms.Room.Rates.Rate rate;

                    /**
                     * Gets the value of the rate property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link CheckRateRS.Hotel.Rooms.Room.Rates.Rate }
                     *     
                     */
                    public CheckRateRS.Hotel.Rooms.Room.Rates.Rate getRate() {
                        return rate;
                    }

                    /**
                     * Sets the value of the rate property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link CheckRateRS.Hotel.Rooms.Room.Rates.Rate }
                     *     
                     */
                    public void setRate(CheckRateRS.Hotel.Rooms.Room.Rates.Rate value) {
                        this.rate = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="cancellationPolicies"&gt;
                     *           &lt;complexType&gt;
                     *             &lt;complexContent&gt;
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                 &lt;sequence&gt;
                     *                   &lt;element name="cancellationPolicy"&gt;
                     *                     &lt;complexType&gt;
                     *                       &lt;simpleContent&gt;
                     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                     *                           &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                     *                           &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
                     *                           &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                     *                         &lt;/extension&gt;
                     *                       &lt;/simpleContent&gt;
                     *                     &lt;/complexType&gt;
                     *                   &lt;/element&gt;
                     *                 &lt;/sequence&gt;
                     *               &lt;/restriction&gt;
                     *             &lt;/complexContent&gt;
                     *           &lt;/complexType&gt;
                     *         &lt;/element&gt;
                     *       &lt;/sequence&gt;
                     *       &lt;attribute name="rateKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="rateClass" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="rateType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="rateComment" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="packaging" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="boardCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="boardName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="rooms" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                     *       &lt;attribute name="adults" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                     *       &lt;attribute name="children" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                     *       &lt;attribute name="net" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "cancellationPolicies"
                    })
                    public static class Rate {

                        @XmlElement(required = true)
                        protected CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies cancellationPolicies;
                        @XmlAttribute(name = "rateKey")
                        protected String rateKey;
                        @XmlAttribute(name = "rateClass")
                        protected String rateClass;
                        @XmlAttribute(name = "rateType")
                        protected String rateType;
                        @XmlAttribute(name = "rateComment")
                        protected String rateComment;
                        @XmlAttribute(name = "paymentType")
                        protected String paymentType;
                        @XmlAttribute(name = "packaging")
                        protected String packaging;
                        @XmlAttribute(name = "boardCode")
                        protected String boardCode;
                        @XmlAttribute(name = "boardName")
                        protected String boardName;
                        @XmlAttribute(name = "rooms")
                        protected Integer rooms;
                        @XmlAttribute(name = "adults")
                        protected Integer adults;
                        @XmlAttribute(name = "children")
                        protected Integer children;
                        @XmlAttribute(name = "net")
                        protected Float net;

                        /**
                         * Gets the value of the cancellationPolicies property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
                         *     
                         */
                        public CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies getCancellationPolicies() {
                            return cancellationPolicies;
                        }

                        /**
                         * Sets the value of the cancellationPolicies property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
                         *     
                         */
                        public void setCancellationPolicies(CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies value) {
                            this.cancellationPolicies = value;
                        }

                        /**
                         * Gets the value of the rateKey property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRateKey() {
                            return rateKey;
                        }

                        /**
                         * Sets the value of the rateKey property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRateKey(String value) {
                            this.rateKey = value;
                        }

                        /**
                         * Gets the value of the rateClass property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRateClass() {
                            return rateClass;
                        }

                        /**
                         * Sets the value of the rateClass property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRateClass(String value) {
                            this.rateClass = value;
                        }

                        /**
                         * Gets the value of the rateType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRateType() {
                            return rateType;
                        }

                        /**
                         * Sets the value of the rateType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRateType(String value) {
                            this.rateType = value;
                        }

                        /**
                         * Gets the value of the rateComment property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRateComment() {
                            return rateComment;
                        }

                        /**
                         * Sets the value of the rateComment property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRateComment(String value) {
                            this.rateComment = value;
                        }

                        /**
                         * Gets the value of the paymentType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPaymentType() {
                            return paymentType;
                        }

                        /**
                         * Sets the value of the paymentType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPaymentType(String value) {
                            this.paymentType = value;
                        }

                        /**
                         * Gets the value of the packaging property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPackaging() {
                            return packaging;
                        }

                        /**
                         * Sets the value of the packaging property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPackaging(String value) {
                            this.packaging = value;
                        }

                        /**
                         * Gets the value of the boardCode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getBoardCode() {
                            return boardCode;
                        }

                        /**
                         * Sets the value of the boardCode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setBoardCode(String value) {
                            this.boardCode = value;
                        }

                        /**
                         * Gets the value of the boardName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getBoardName() {
                            return boardName;
                        }

                        /**
                         * Sets the value of the boardName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setBoardName(String value) {
                            this.boardName = value;
                        }

                        /**
                         * Gets the value of the rooms property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Integer }
                         *     
                         */
                        public Integer getRooms() {
                            return rooms;
                        }

                        /**
                         * Sets the value of the rooms property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Integer }
                         *     
                         */
                        public void setRooms(Integer value) {
                            this.rooms = value;
                        }

                        /**
                         * Gets the value of the adults property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Integer }
                         *     
                         */
                        public Integer getAdults() {
                            return adults;
                        }

                        /**
                         * Sets the value of the adults property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Integer }
                         *     
                         */
                        public void setAdults(Integer value) {
                            this.adults = value;
                        }

                        /**
                         * Gets the value of the children property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Integer }
                         *     
                         */
                        public Integer getChildren() {
                            return children;
                        }

                        /**
                         * Sets the value of the children property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Integer }
                         *     
                         */
                        public void setChildren(Integer value) {
                            this.children = value;
                        }

                        /**
                         * Gets the value of the net property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Float }
                         *     
                         */
                        public Float getNet() {
                            return net;
                        }

                        /**
                         * Sets the value of the net property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Float }
                         *     
                         */
                        public void setNet(Float value) {
                            this.net = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType&gt;
                         *   &lt;complexContent&gt;
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *       &lt;sequence&gt;
                         *         &lt;element name="cancellationPolicy"&gt;
                         *           &lt;complexType&gt;
                         *             &lt;simpleContent&gt;
                         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                         *                 &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                         *                 &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
                         *                 &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                         *               &lt;/extension&gt;
                         *             &lt;/simpleContent&gt;
                         *           &lt;/complexType&gt;
                         *         &lt;/element&gt;
                         *       &lt;/sequence&gt;
                         *     &lt;/restriction&gt;
                         *   &lt;/complexContent&gt;
                         * &lt;/complexType&gt;
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "cancellationPolicy"
                        })
                        public static class CancellationPolicies {

                            @XmlElement(required = true)
                            protected CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy cancellationPolicy;

                            /**
                             * Gets the value of the cancellationPolicy property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
                             *     
                             */
                            public CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy getCancellationPolicy() {
                                return cancellationPolicy;
                            }

                            /**
                             * Sets the value of the cancellationPolicy property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
                             *     
                             */
                            public void setCancellationPolicy(CheckRateRS.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy value) {
                                this.cancellationPolicy = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType&gt;
                             *   &lt;simpleContent&gt;
                             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                             *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                             *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
                             *       &lt;attribute name="hotelAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
                             *     &lt;/extension&gt;
                             *   &lt;/simpleContent&gt;
                             * &lt;/complexType&gt;
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class CancellationPolicy {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "amount")
                                protected Float amount;
                                @XmlAttribute(name = "from")
                                @XmlSchemaType(name = "date")
                                protected XMLGregorianCalendar from;
                                @XmlAttribute(name = "hotelAmount")
                                protected Float hotelAmount;

                                /**
                                 * Gets the value of the value property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getValue() {
                                    return value;
                                }

                                /**
                                 * Sets the value of the value property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                /**
                                 * Gets the value of the amount property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Float }
                                 *     
                                 */
                                public Float getAmount() {
                                    return amount;
                                }

                                /**
                                 * Sets the value of the amount property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Float }
                                 *     
                                 */
                                public void setAmount(Float value) {
                                    this.amount = value;
                                }

                                /**
                                 * Gets the value of the from property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link XMLGregorianCalendar }
                                 *     
                                 */
                                public XMLGregorianCalendar getFrom() {
                                    return from;
                                }

                                /**
                                 * Sets the value of the from property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link XMLGregorianCalendar }
                                 *     
                                 */
                                public void setFrom(XMLGregorianCalendar value) {
                                    this.from = value;
                                }

                                /**
                                 * Gets the value of the hotelAmount property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link Float }
                                 *     
                                 */
                                public Float getHotelAmount() {
                                    return hotelAmount;
                                }

                                /**
                                 * Sets the value of the hotelAmount property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link Float }
                                 *     
                                 */
                                public void setHotelAmount(Float value) {
                                    this.hotelAmount = value;
                                }

                            }

                        }

                    }

                }

            }

        }

    }

}
