//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 06:24:53 PM IST 
//


package com.bonton.utility.hotelbeds;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bonton.utility.hotelbeds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bonton.utility.hotelbeds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AvailabilityRQ }
     * 
     */
    public AvailabilityRQ createAvailabilityRQ() {
        return new AvailabilityRQ();
    }

    /**
     * Create an instance of {@link AvailabilityRS }
     * 
     */
    public AvailabilityRS createAvailabilityRS() {
        return new AvailabilityRS();
    }

    /**
     * Create an instance of {@link BookingRS }
     * 
     */
    public BookingRS createBookingRS() {
        return new BookingRS();
    }

    /**
     * Create an instance of {@link BookingCancellationRS }
     * 
     */
    public BookingCancellationRS createBookingCancellationRS() {
        return new BookingCancellationRS();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking }
     * 
     */
    public BookingCancellationRS.Booking createBookingCancellationRSBooking() {
        return new BookingCancellationRS.Booking();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel }
     * 
     */
    public BookingCancellationRS.Booking.Hotel createBookingCancellationRSBookingHotel() {
        return new BookingCancellationRS.Booking.Hotel();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms createBookingCancellationRSBookingHotelRooms() {
        return new BookingCancellationRS.Booking.Hotel.Rooms();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room createBookingCancellationRSBookingHotelRoomsRoom() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates createBookingCancellationRSBookingHotelRoomsRoomRates() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate createBookingCancellationRSBookingHotelRoomsRoomRatesRate() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown createBookingCancellationRSBookingHotelRoomsRoomRatesRateRateBreakDown() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements createBookingCancellationRSBookingHotelRoomsRoomRatesRateRateBreakDownRateSupplements() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies createBookingCancellationRSBookingHotelRoomsRoomRatesRateCancellationPolicies() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Paxes }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Paxes createBookingCancellationRSBookingHotelRoomsRoomPaxes() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Paxes();
    }

    /**
     * Create an instance of {@link BookingRS.Booking }
     * 
     */
    public BookingRS.Booking createBookingRSBooking() {
        return new BookingRS.Booking();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel }
     * 
     */
    public BookingRS.Booking.Hotel createBookingRSBookingHotel() {
        return new BookingRS.Booking.Hotel();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms createBookingRSBookingHotelRooms() {
        return new BookingRS.Booking.Hotel.Rooms();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room createBookingRSBookingHotelRoomsRoom() {
        return new BookingRS.Booking.Hotel.Rooms.Room();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Rates }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Rates createBookingRSBookingHotelRoomsRoomRates() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Rates();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate createBookingRSBookingHotelRoomsRoomRatesRate() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown createBookingRSBookingHotelRoomsRoomRatesRateRateBreakDown() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements createBookingRSBookingHotelRoomsRoomRatesRateRateBreakDownRateSupplements() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies createBookingRSBookingHotelRoomsRoomRatesRateCancellationPolicies() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Paxes }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Paxes createBookingRSBookingHotelRoomsRoomPaxes() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Paxes();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels }
     * 
     */
    public AvailabilityRS.Hotels createAvailabilityRSHotels() {
        return new AvailabilityRS.Hotels();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel }
     * 
     */
    public AvailabilityRS.Hotels.Hotel createAvailabilityRSHotelsHotel() {
        return new AvailabilityRS.Hotels.Hotel();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms createAvailabilityRSHotelsHotelRooms() {
        return new AvailabilityRS.Hotels.Hotel.Rooms();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room createAvailabilityRSHotelsHotelRoomsRoom() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates createAvailabilityRSHotelsHotelRoomsRoomRates() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate createAvailabilityRSHotelsHotelRoomsRoomRatesRate() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies createAvailabilityRSHotelsHotelRoomsRoomRatesRateCancellationPolicies() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies }
     * 
     */
    public AvailabilityRQ.Occupancies createAvailabilityRQOccupancies() {
        return new AvailabilityRQ.Occupancies();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies.Occupancy }
     * 
     */
    public AvailabilityRQ.Occupancies.Occupancy createAvailabilityRQOccupanciesOccupancy() {
        return new AvailabilityRQ.Occupancies.Occupancy();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies.Occupancy.Paxes }
     * 
     */
    public AvailabilityRQ.Occupancies.Occupancy.Paxes createAvailabilityRQOccupanciesOccupancyPaxes() {
        return new AvailabilityRQ.Occupancies.Occupancy.Paxes();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Stay }
     * 
     */
    public AvailabilityRQ.Stay createAvailabilityRQStay() {
        return new AvailabilityRQ.Stay();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Destination }
     * 
     */
    public AvailabilityRQ.Destination createAvailabilityRQDestination() {
        return new AvailabilityRQ.Destination();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Hotels }
     * 
     */
    public AvailabilityRQ.Hotels createAvailabilityRQHotels() {
        return new AvailabilityRQ.Hotels();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Filter }
     * 
     */
    public AvailabilityRQ.Filter createAvailabilityRQFilter() {
        return new AvailabilityRQ.Filter();
    }

    /**
     * Create an instance of {@link ErrorRS }
     * 
     */
    public ErrorRS createErrorRS() {
        return new ErrorRS();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.ModificationPolicies }
     * 
     */
    public BookingCancellationRS.Booking.ModificationPolicies createBookingCancellationRSBookingModificationPolicies() {
        return new BookingCancellationRS.Booking.ModificationPolicies();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Holder }
     * 
     */
    public BookingCancellationRS.Booking.Holder createBookingCancellationRSBookingHolder() {
        return new BookingCancellationRS.Booking.Holder();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Supplier }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Supplier createBookingCancellationRSBookingHotelSupplier() {
        return new BookingCancellationRS.Booking.Hotel.Supplier();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements.RateSupplement }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements.RateSupplement createBookingCancellationRSBookingHotelRoomsRoomRatesRateRateBreakDownRateSupplementsRateSupplement() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements.RateSupplement();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy createBookingCancellationRSBookingHotelRoomsRoomRatesRateCancellationPoliciesCancellationPolicy() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy();
    }

    /**
     * Create an instance of {@link BookingCancellationRS.Booking.Hotel.Rooms.Room.Paxes.Pax }
     * 
     */
    public BookingCancellationRS.Booking.Hotel.Rooms.Room.Paxes.Pax createBookingCancellationRSBookingHotelRoomsRoomPaxesPax() {
        return new BookingCancellationRS.Booking.Hotel.Rooms.Room.Paxes.Pax();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.ModificationPolicies }
     * 
     */
    public BookingRS.Booking.ModificationPolicies createBookingRSBookingModificationPolicies() {
        return new BookingRS.Booking.ModificationPolicies();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Holder }
     * 
     */
    public BookingRS.Booking.Holder createBookingRSBookingHolder() {
        return new BookingRS.Booking.Holder();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Supplier }
     * 
     */
    public BookingRS.Booking.Hotel.Supplier createBookingRSBookingHotelSupplier() {
        return new BookingRS.Booking.Hotel.Supplier();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements.RateSupplement }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements.RateSupplement createBookingRSBookingHotelRoomsRoomRatesRateRateBreakDownRateSupplementsRateSupplement() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.RateBreakDown.RateSupplements.RateSupplement();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy createBookingRSBookingHotelRoomsRoomRatesRateCancellationPoliciesCancellationPolicy() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy();
    }

    /**
     * Create an instance of {@link BookingRS.Booking.Hotel.Rooms.Room.Paxes.Pax }
     * 
     */
    public BookingRS.Booking.Hotel.Rooms.Room.Paxes.Pax createBookingRSBookingHotelRoomsRoomPaxesPax() {
        return new BookingRS.Booking.Hotel.Rooms.Room.Paxes.Pax();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy createAvailabilityRSHotelsHotelRoomsRoomRatesRateCancellationPoliciesCancellationPolicy() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies.Occupancy.Paxes.Pax }
     * 
     */
    public AvailabilityRQ.Occupancies.Occupancy.Paxes.Pax createAvailabilityRQOccupanciesOccupancyPaxesPax() {
        return new AvailabilityRQ.Occupancies.Occupancy.Paxes.Pax();
    }

}
