//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.12 at 03:55:31 PM IST 
//


package com.bonton.utility.hotelbeds;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bonton.utility.hotelbeds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bonton.utility.hotelbeds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AvailabilityRQ }
     * 
     */
    public AvailabilityRQ createAvailabilityRQ() {
        return new AvailabilityRQ();
    }

    /**
     * Create an instance of {@link AvailabilityRS }
     * 
     */
    public AvailabilityRS createAvailabilityRS() {
        return new AvailabilityRS();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels }
     * 
     */
    public AvailabilityRS.Hotels createAvailabilityRSHotels() {
        return new AvailabilityRS.Hotels();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel }
     * 
     */
    public AvailabilityRS.Hotels.Hotel createAvailabilityRSHotelsHotel() {
        return new AvailabilityRS.Hotels.Hotel();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms createAvailabilityRSHotelsHotelRooms() {
        return new AvailabilityRS.Hotels.Hotel.Rooms();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room createAvailabilityRSHotelsHotelRoomsRoom() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates createAvailabilityRSHotelsHotelRoomsRoomRates() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate createAvailabilityRSHotelsHotelRoomsRoomRatesRate() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies createAvailabilityRSHotelsHotelRoomsRoomRatesRateCancellationPolicies() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies }
     * 
     */
    public AvailabilityRQ.Occupancies createAvailabilityRQOccupancies() {
        return new AvailabilityRQ.Occupancies();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies.Occupancy }
     * 
     */
    public AvailabilityRQ.Occupancies.Occupancy createAvailabilityRQOccupanciesOccupancy() {
        return new AvailabilityRQ.Occupancies.Occupancy();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies.Occupancy.Paxes }
     * 
     */
    public AvailabilityRQ.Occupancies.Occupancy.Paxes createAvailabilityRQOccupanciesOccupancyPaxes() {
        return new AvailabilityRQ.Occupancies.Occupancy.Paxes();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Stay }
     * 
     */
    public AvailabilityRQ.Stay createAvailabilityRQStay() {
        return new AvailabilityRQ.Stay();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Destination }
     * 
     */
    public AvailabilityRQ.Destination createAvailabilityRQDestination() {
        return new AvailabilityRQ.Destination();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Hotels }
     * 
     */
    public AvailabilityRQ.Hotels createAvailabilityRQHotels() {
        return new AvailabilityRQ.Hotels();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Filter }
     * 
     */
    public AvailabilityRQ.Filter createAvailabilityRQFilter() {
        return new AvailabilityRQ.Filter();
    }

    /**
     * Create an instance of {@link AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
     * 
     */
    public AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy createAvailabilityRSHotelsHotelRoomsRoomRatesRateCancellationPoliciesCancellationPolicy() {
        return new AvailabilityRS.Hotels.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy();
    }

    /**
     * Create an instance of {@link AvailabilityRQ.Occupancies.Occupancy.Paxes.Pax }
     * 
     */
    public AvailabilityRQ.Occupancies.Occupancy.Paxes.Pax createAvailabilityRQOccupanciesOccupancyPaxesPax() {
        return new AvailabilityRQ.Occupancies.Occupancy.Paxes.Pax();
    }

}
