//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 12:07:09 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hotelbeds.com/schemas/messages",
elementFormDefault = XmlNsForm.QUALIFIED,
xmlns={@XmlNs(prefix="", namespaceURI="http://www.hotelbeds.com/schemas/messages")})
package com.bonton.utility.hotelbeds;
import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;

