//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.10 at 02:12:38 PM IST 
//


package com.bonton.utility.desia;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.desia.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.desia.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Hotels }
     * 
     */
    public Hotels createHotels() {
        return new Hotels();
    }

    /**
     * Create an instance of {@link Hotels.Hotel }
     * 
     */
    public Hotels.Hotel createHotelsHotel() {
        return new Hotels.Hotel();
    }

    /**
     * Create an instance of {@link Hotels.Hotel.Rooms }
     * 
     */
    public Hotels.Hotel.Rooms createHotelsHotelRooms() {
        return new Hotels.Hotel.Rooms();
    }

    /**
     * Create an instance of {@link Hotels.Hotel.Rooms.Room }
     * 
     */
    public Hotels.Hotel.Rooms.Room createHotelsHotelRoomsRoom() {
        return new Hotels.Hotel.Rooms.Room();
    }

    /**
     * Create an instance of {@link Hotels.Hotel.Rooms.Room.Rate }
     * 
     */
    public Hotels.Hotel.Rooms.Room.Rate createHotelsHotelRoomsRoomRate() {
        return new Hotels.Hotel.Rooms.Room.Rate();
    }

    /**
     * Create an instance of {@link Hotels.Hotel.Rooms.Room.Rate.Offers }
     * 
     */
    public Hotels.Hotel.Rooms.Room.Rate.Offers createHotelsHotelRoomsRoomRateOffers() {
        return new Hotels.Hotel.Rooms.Room.Rate.Offers();
    }

    /**
     * Create an instance of {@link Hotels.Hotel.Rooms.Room.Cancellation }
     * 
     */
    public Hotels.Hotel.Rooms.Room.Cancellation createHotelsHotelRoomsRoomCancellation() {
        return new Hotels.Hotel.Rooms.Room.Cancellation();
    }

    /**
     * Create an instance of {@link Hotels.Hotel.Rooms.Room.Rate.Offers.Offer }
     * 
     */
    public Hotels.Hotel.Rooms.Room.Rate.Offers.Offer createHotelsHotelRoomsRoomRateOffersOffer() {
        return new Hotels.Hotel.Rooms.Room.Rate.Offers.Offer();
    }

}
