//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.08 at 06:31:48 PM IST 
//


package com.desia.reprice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.desia.reprice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.desia.reprice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BTNRepriceRequest }
     * 
     */
    public BTNRepriceRequest createBTNRepriceRequest() {
        return new BTNRepriceRequest();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse }
     * 
     */
    public BTNRepriceResponse createBTNRepriceResponse() {
        return new BTNRepriceResponse();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel }
     * 
     */
    public BTNRepriceResponse.Hotel createBTNRepriceResponseHotel() {
        return new BTNRepriceResponse.Hotel();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.CreditCards }
     * 
     */
    public BTNRepriceResponse.Hotel.CreditCards createBTNRepriceResponseHotelCreditCards() {
        return new BTNRepriceResponse.Hotel.CreditCards();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.Rooms }
     * 
     */
    public BTNRepriceResponse.Hotel.Rooms createBTNRepriceResponseHotelRooms() {
        return new BTNRepriceResponse.Hotel.Rooms();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.Rooms.Room }
     * 
     */
    public BTNRepriceResponse.Hotel.Rooms.Room createBTNRepriceResponseHotelRoomsRoom() {
        return new BTNRepriceResponse.Hotel.Rooms.Room();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates }
     * 
     */
    public BTNRepriceResponse.Hotel.Rooms.Room.Rates createBTNRepriceResponseHotelRoomsRoomRates() {
        return new BTNRepriceResponse.Hotel.Rooms.Room.Rates();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate }
     * 
     */
    public BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate createBTNRepriceResponseHotelRoomsRoomRatesRate() {
        return new BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
     * 
     */
    public BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies createBTNRepriceResponseHotelRoomsRoomRatesRateCancellationPolicies() {
        return new BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies();
    }

    /**
     * Create an instance of {@link BTNRepriceRequest.Rooms }
     * 
     */
    public BTNRepriceRequest.Rooms createBTNRepriceRequestRooms() {
        return new BTNRepriceRequest.Rooms();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.CreditCards.CreditCard }
     * 
     */
    public BTNRepriceResponse.Hotel.CreditCards.CreditCard createBTNRepriceResponseHotelCreditCardsCreditCard() {
        return new BTNRepriceResponse.Hotel.CreditCards.CreditCard();
    }

    /**
     * Create an instance of {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
     * 
     */
    public BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy createBTNRepriceResponseHotelRoomsRoomRatesRateCancellationPoliciesCancellationPolicy() {
        return new BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy();
    }

    /**
     * Create an instance of {@link BTNRepriceRequest.Rooms.Room }
     * 
     */
    public BTNRepriceRequest.Rooms.Room createBTNRepriceRequestRoomsRoom() {
        return new BTNRepriceRequest.Rooms.Room();
    }

}
