//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.25 at 02:34:03 PM IST 
//


package com.bonton.utility.artifacts;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Hotel"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Rooms"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Room" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Rates"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="Rate"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="NetRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                                           &lt;element name="Packaging" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="RateType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="RateComments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="RoomCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                                           &lt;element name="AdultCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                                           &lt;element name="ChildCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                                           &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                                           &lt;element name="CancellationPolicies"&gt;
 *                                                             &lt;complexType&gt;
 *                                                               &lt;complexContent&gt;
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                   &lt;sequence&gt;
 *                                                                     &lt;element name="CancellationPolicy"&gt;
 *                                                                       &lt;complexType&gt;
 *                                                                         &lt;simpleContent&gt;
 *                                                                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                                                             &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                                                                             &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                                                                           &lt;/extension&gt;
 *                                                                         &lt;/simpleContent&gt;
 *                                                                       &lt;/complexType&gt;
 *                                                                     &lt;/element&gt;
 *                                                                   &lt;/sequence&gt;
 *                                                                 &lt;/restriction&gt;
 *                                                               &lt;/complexContent&gt;
 *                                                             &lt;/complexType&gt;
 *                                                           &lt;/element&gt;
 *                                                         &lt;/sequence&gt;
 *                                                         &lt;attribute name="uniqueKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="CreditCards"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CreditCard" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="checkIn" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                 &lt;attribute name="checkOut" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="destinationCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="destinationName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Supplier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BTNError"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hotel",
    "supplier",
    "btnError"
})
@XmlRootElement(name = "BTNRepriceResponse")
public class BTNRepriceResponse {

    @XmlElement(name = "Hotel", required = true)
    protected BTNRepriceResponse.Hotel hotel;
    @XmlElement(name = "Supplier", required = true)
    protected String supplier;
    @XmlElement(name = "BTNError", required = true)
    protected BTNRepriceResponse.BTNError btnError;

    /**
     * Gets the value of the hotel property.
     * 
     * @return
     *     possible object is
     *     {@link BTNRepriceResponse.Hotel }
     *     
     */
    public BTNRepriceResponse.Hotel getHotel() {
        return hotel;
    }

    /**
     * Sets the value of the hotel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BTNRepriceResponse.Hotel }
     *     
     */
    public void setHotel(BTNRepriceResponse.Hotel value) {
        this.hotel = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplier(String value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the btnError property.
     * 
     * @return
     *     possible object is
     *     {@link BTNRepriceResponse.BTNError }
     *     
     */
    public BTNRepriceResponse.BTNError getBTNError() {
        return btnError;
    }

    /**
     * Sets the value of the btnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link BTNRepriceResponse.BTNError }
     *     
     */
    public void setBTNError(BTNRepriceResponse.BTNError value) {
        this.btnError = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "message"
    })
    public static class BTNError {

        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String message;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Rooms"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Room" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Rates"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="Rate"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="NetRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                                                 &lt;element name="Packaging" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="RateType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="RateComments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="RoomCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                                                 &lt;element name="AdultCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                                                 &lt;element name="ChildCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                                                 &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                                                 &lt;element name="CancellationPolicies"&gt;
     *                                                   &lt;complexType&gt;
     *                                                     &lt;complexContent&gt;
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                         &lt;sequence&gt;
     *                                                           &lt;element name="CancellationPolicy"&gt;
     *                                                             &lt;complexType&gt;
     *                                                               &lt;simpleContent&gt;
     *                                                                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                                                                   &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *                                                                   &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *                                                                 &lt;/extension&gt;
     *                                                               &lt;/simpleContent&gt;
     *                                                             &lt;/complexType&gt;
     *                                                           &lt;/element&gt;
     *                                                         &lt;/sequence&gt;
     *                                                       &lt;/restriction&gt;
     *                                                     &lt;/complexContent&gt;
     *                                                   &lt;/complexType&gt;
     *                                                 &lt;/element&gt;
     *                                               &lt;/sequence&gt;
     *                                               &lt;attribute name="uniqueKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="CreditCards"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="CreditCard" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="checkIn" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *       &lt;attribute name="checkOut" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="destinationCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="destinationName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rooms",
        "creditCards"
    })
    public static class Hotel {

        @XmlElement(name = "Rooms", required = true)
        protected BTNRepriceResponse.Hotel.Rooms rooms;
        @XmlElement(name = "CreditCards", required = true)
        protected BTNRepriceResponse.Hotel.CreditCards creditCards;
        @XmlAttribute(name = "checkIn")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar checkIn;
        @XmlAttribute(name = "checkOut")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar checkOut;
        @XmlAttribute(name = "code")
        protected Integer code;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "categoryCode")
        protected String categoryCode;
        @XmlAttribute(name = "categoryName")
        protected String categoryName;
        @XmlAttribute(name = "destinationCode")
        protected String destinationCode;
        @XmlAttribute(name = "destinationName")
        protected String destinationName;

        /**
         * Gets the value of the rooms property.
         * 
         * @return
         *     possible object is
         *     {@link BTNRepriceResponse.Hotel.Rooms }
         *     
         */
        public BTNRepriceResponse.Hotel.Rooms getRooms() {
            return rooms;
        }

        /**
         * Sets the value of the rooms property.
         * 
         * @param value
         *     allowed object is
         *     {@link BTNRepriceResponse.Hotel.Rooms }
         *     
         */
        public void setRooms(BTNRepriceResponse.Hotel.Rooms value) {
            this.rooms = value;
        }

        /**
         * Gets the value of the creditCards property.
         * 
         * @return
         *     possible object is
         *     {@link BTNRepriceResponse.Hotel.CreditCards }
         *     
         */
        public BTNRepriceResponse.Hotel.CreditCards getCreditCards() {
            return creditCards;
        }

        /**
         * Sets the value of the creditCards property.
         * 
         * @param value
         *     allowed object is
         *     {@link BTNRepriceResponse.Hotel.CreditCards }
         *     
         */
        public void setCreditCards(BTNRepriceResponse.Hotel.CreditCards value) {
            this.creditCards = value;
        }

        /**
         * Gets the value of the checkIn property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCheckIn() {
            return checkIn;
        }

        /**
         * Sets the value of the checkIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCheckIn(XMLGregorianCalendar value) {
            this.checkIn = value;
        }

        /**
         * Gets the value of the checkOut property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCheckOut() {
            return checkOut;
        }

        /**
         * Sets the value of the checkOut property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCheckOut(XMLGregorianCalendar value) {
            this.checkOut = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCode(Integer value) {
            this.code = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the categoryCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryCode() {
            return categoryCode;
        }

        /**
         * Sets the value of the categoryCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryCode(String value) {
            this.categoryCode = value;
        }

        /**
         * Gets the value of the categoryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategoryName() {
            return categoryName;
        }

        /**
         * Sets the value of the categoryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategoryName(String value) {
            this.categoryName = value;
        }

        /**
         * Gets the value of the destinationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationCode() {
            return destinationCode;
        }

        /**
         * Sets the value of the destinationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationCode(String value) {
            this.destinationCode = value;
        }

        /**
         * Gets the value of the destinationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationName() {
            return destinationName;
        }

        /**
         * Sets the value of the destinationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationName(String value) {
            this.destinationName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="CreditCard" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "creditCard"
        })
        public static class CreditCards {

            @XmlElement(name = "CreditCard")
            protected List<BTNRepriceResponse.Hotel.CreditCards.CreditCard> creditCard;

            /**
             * Gets the value of the creditCard property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the creditCard property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCreditCard().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BTNRepriceResponse.Hotel.CreditCards.CreditCard }
             * 
             * 
             */
            public List<BTNRepriceResponse.Hotel.CreditCards.CreditCard> getCreditCard() {
                if (creditCard == null) {
                    creditCard = new ArrayList<BTNRepriceResponse.Hotel.CreditCards.CreditCard>();
                }
                return this.creditCard;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="paymentType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class CreditCard {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "code")
                protected String code;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "paymentType")
                protected String paymentType;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the paymentType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPaymentType() {
                    return paymentType;
                }

                /**
                 * Sets the value of the paymentType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPaymentType(String value) {
                    this.paymentType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Room" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Rates"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="Rate"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="NetRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
         *                                       &lt;element name="Packaging" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="RateType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="RateComments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="RoomCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                                       &lt;element name="AdultCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                                       &lt;element name="ChildCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                                       &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                                       &lt;element name="CancellationPolicies"&gt;
         *                                         &lt;complexType&gt;
         *                                           &lt;complexContent&gt;
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                               &lt;sequence&gt;
         *                                                 &lt;element name="CancellationPolicy"&gt;
         *                                                   &lt;complexType&gt;
         *                                                     &lt;simpleContent&gt;
         *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                                                         &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *                                                         &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         *                                                       &lt;/extension&gt;
         *                                                     &lt;/simpleContent&gt;
         *                                                   &lt;/complexType&gt;
         *                                                 &lt;/element&gt;
         *                                               &lt;/sequence&gt;
         *                                             &lt;/restriction&gt;
         *                                           &lt;/complexContent&gt;
         *                                         &lt;/complexType&gt;
         *                                       &lt;/element&gt;
         *                                     &lt;/sequence&gt;
         *                                     &lt;attribute name="uniqueKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "room"
        })
        public static class Rooms {

            @XmlElement(name = "Room", required = true)
            protected List<BTNRepriceResponse.Hotel.Rooms.Room> room;

            /**
             * Gets the value of the room property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the room property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRoom().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BTNRepriceResponse.Hotel.Rooms.Room }
             * 
             * 
             */
            public List<BTNRepriceResponse.Hotel.Rooms.Room> getRoom() {
                if (room == null) {
                    room = new ArrayList<BTNRepriceResponse.Hotel.Rooms.Room>();
                }
                return this.room;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Rates"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="Rate"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="NetRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
             *                             &lt;element name="Packaging" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="RateType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="RateComments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="RoomCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *                             &lt;element name="AdultCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *                             &lt;element name="ChildCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *                             &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *                             &lt;element name="CancellationPolicies"&gt;
             *                               &lt;complexType&gt;
             *                                 &lt;complexContent&gt;
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                     &lt;sequence&gt;
             *                                       &lt;element name="CancellationPolicy"&gt;
             *                                         &lt;complexType&gt;
             *                                           &lt;simpleContent&gt;
             *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *                                               &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
             *                                               &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
             *                                             &lt;/extension&gt;
             *                                           &lt;/simpleContent&gt;
             *                                         &lt;/complexType&gt;
             *                                       &lt;/element&gt;
             *                                     &lt;/sequence&gt;
             *                                   &lt;/restriction&gt;
             *                                 &lt;/complexContent&gt;
             *                               &lt;/complexType&gt;
             *                             &lt;/element&gt;
             *                           &lt;/sequence&gt;
             *                           &lt;attribute name="uniqueKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "rates"
            })
            public static class Room {

                @XmlElement(name = "Rates", required = true)
                protected BTNRepriceResponse.Hotel.Rooms.Room.Rates rates;
                @XmlAttribute(name = "code")
                protected String code;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the rates property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates }
                 *     
                 */
                public BTNRepriceResponse.Hotel.Rooms.Room.Rates getRates() {
                    return rates;
                }

                /**
                 * Sets the value of the rates property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates }
                 *     
                 */
                public void setRates(BTNRepriceResponse.Hotel.Rooms.Room.Rates value) {
                    this.rates = value;
                }

                /**
                 * Gets the value of the code property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="Rate"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="NetRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
                 *                   &lt;element name="Packaging" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="RateType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="RateComments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="RoomCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                 *                   &lt;element name="AdultCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                 *                   &lt;element name="ChildCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                 *                   &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                 *                   &lt;element name="CancellationPolicies"&gt;
                 *                     &lt;complexType&gt;
                 *                       &lt;complexContent&gt;
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                           &lt;sequence&gt;
                 *                             &lt;element name="CancellationPolicy"&gt;
                 *                               &lt;complexType&gt;
                 *                                 &lt;simpleContent&gt;
                 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                 *                                     &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
                 *                                     &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
                 *                                   &lt;/extension&gt;
                 *                                 &lt;/simpleContent&gt;
                 *                               &lt;/complexType&gt;
                 *                             &lt;/element&gt;
                 *                           &lt;/sequence&gt;
                 *                         &lt;/restriction&gt;
                 *                       &lt;/complexContent&gt;
                 *                     &lt;/complexType&gt;
                 *                   &lt;/element&gt;
                 *                 &lt;/sequence&gt;
                 *                 &lt;attribute name="uniqueKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "rate"
                })
                public static class Rates {

                    @XmlElement(name = "Rate", required = true)
                    protected BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate rate;

                    /**
                     * Gets the value of the rate property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate }
                     *     
                     */
                    public BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate getRate() {
                        return rate;
                    }

                    /**
                     * Sets the value of the rate property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate }
                     *     
                     */
                    public void setRate(BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate value) {
                        this.rate = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="NetRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
                     *         &lt;element name="Packaging" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="RateType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="RateComments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="RoomCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                     *         &lt;element name="AdultCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                     *         &lt;element name="ChildCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                     *         &lt;element name="ChildrenAges" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
                     *         &lt;element name="CancellationPolicies"&gt;
                     *           &lt;complexType&gt;
                     *             &lt;complexContent&gt;
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                 &lt;sequence&gt;
                     *                   &lt;element name="CancellationPolicy"&gt;
                     *                     &lt;complexType&gt;
                     *                       &lt;simpleContent&gt;
                     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                     *                           &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
                     *                           &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
                     *                         &lt;/extension&gt;
                     *                       &lt;/simpleContent&gt;
                     *                     &lt;/complexType&gt;
                     *                   &lt;/element&gt;
                     *                 &lt;/sequence&gt;
                     *               &lt;/restriction&gt;
                     *             &lt;/complexContent&gt;
                     *           &lt;/complexType&gt;
                     *         &lt;/element&gt;
                     *       &lt;/sequence&gt;
                     *       &lt;attribute name="uniqueKey" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "netRate",
                        "packaging",
                        "rateType",
                        "rateComments",
                        "category",
                        "roomCount",
                        "adultCount",
                        "childCount",
                        "childrenAges",
                        "cancellationPolicies"
                    })
                    public static class Rate {

                        @XmlElement(name = "NetRate", required = true)
                        protected BigDecimal netRate;
                        @XmlElement(name = "Packaging", required = true)
                        protected String packaging;
                        @XmlElement(name = "RateType", required = true)
                        protected String rateType;
                        @XmlElement(name = "RateComments", required = true)
                        protected String rateComments;
                        @XmlElement(name = "Category", required = true)
                        protected String category;
                        @XmlElement(name = "RoomCount")
                        protected int roomCount;
                        @XmlElement(name = "AdultCount")
                        protected int adultCount;
                        @XmlElement(name = "ChildCount")
                        protected int childCount;
                        @XmlElement(name = "ChildrenAges")
                        protected int childrenAges;
                        @XmlElement(name = "CancellationPolicies", required = true)
                        protected BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies cancellationPolicies;
                        @XmlAttribute(name = "uniqueKey")
                        protected String uniqueKey;

                        /**
                         * Gets the value of the netRate property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public BigDecimal getNetRate() {
                            return netRate;
                        }

                        /**
                         * Sets the value of the netRate property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public void setNetRate(BigDecimal value) {
                            this.netRate = value;
                        }

                        /**
                         * Gets the value of the packaging property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPackaging() {
                            return packaging;
                        }

                        /**
                         * Sets the value of the packaging property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPackaging(String value) {
                            this.packaging = value;
                        }

                        /**
                         * Gets the value of the rateType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRateType() {
                            return rateType;
                        }

                        /**
                         * Sets the value of the rateType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRateType(String value) {
                            this.rateType = value;
                        }

                        /**
                         * Gets the value of the rateComments property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRateComments() {
                            return rateComments;
                        }

                        /**
                         * Sets the value of the rateComments property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRateComments(String value) {
                            this.rateComments = value;
                        }

                        /**
                         * Gets the value of the category property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCategory() {
                            return category;
                        }

                        /**
                         * Sets the value of the category property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCategory(String value) {
                            this.category = value;
                        }

                        /**
                         * Gets the value of the roomCount property.
                         * 
                         */
                        public int getRoomCount() {
                            return roomCount;
                        }

                        /**
                         * Sets the value of the roomCount property.
                         * 
                         */
                        public void setRoomCount(int value) {
                            this.roomCount = value;
                        }

                        /**
                         * Gets the value of the adultCount property.
                         * 
                         */
                        public int getAdultCount() {
                            return adultCount;
                        }

                        /**
                         * Sets the value of the adultCount property.
                         * 
                         */
                        public void setAdultCount(int value) {
                            this.adultCount = value;
                        }

                        /**
                         * Gets the value of the childCount property.
                         * 
                         */
                        public int getChildCount() {
                            return childCount;
                        }

                        /**
                         * Sets the value of the childCount property.
                         * 
                         */
                        public void setChildCount(int value) {
                            this.childCount = value;
                        }

                        /**
                         * Gets the value of the childrenAges property.
                         * 
                         */
                        public int getChildrenAges() {
                            return childrenAges;
                        }

                        /**
                         * Sets the value of the childrenAges property.
                         * 
                         */
                        public void setChildrenAges(int value) {
                            this.childrenAges = value;
                        }

                        /**
                         * Gets the value of the cancellationPolicies property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
                         *     
                         */
                        public BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies getCancellationPolicies() {
                            return cancellationPolicies;
                        }

                        /**
                         * Sets the value of the cancellationPolicies property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies }
                         *     
                         */
                        public void setCancellationPolicies(BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies value) {
                            this.cancellationPolicies = value;
                        }

                        /**
                         * Gets the value of the uniqueKey property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getUniqueKey() {
                            return uniqueKey;
                        }

                        /**
                         * Sets the value of the uniqueKey property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setUniqueKey(String value) {
                            this.uniqueKey = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType&gt;
                         *   &lt;complexContent&gt;
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *       &lt;sequence&gt;
                         *         &lt;element name="CancellationPolicy"&gt;
                         *           &lt;complexType&gt;
                         *             &lt;simpleContent&gt;
                         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                         *                 &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
                         *                 &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
                         *               &lt;/extension&gt;
                         *             &lt;/simpleContent&gt;
                         *           &lt;/complexType&gt;
                         *         &lt;/element&gt;
                         *       &lt;/sequence&gt;
                         *     &lt;/restriction&gt;
                         *   &lt;/complexContent&gt;
                         * &lt;/complexType&gt;
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "cancellationPolicy"
                        })
                        public static class CancellationPolicies {

                            @XmlElement(name = "CancellationPolicy", required = true)
                            protected BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy cancellationPolicy;

                            /**
                             * Gets the value of the cancellationPolicy property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
                             *     
                             */
                            public BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy getCancellationPolicy() {
                                return cancellationPolicy;
                            }

                            /**
                             * Sets the value of the cancellationPolicy property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy }
                             *     
                             */
                            public void setCancellationPolicy(BTNRepriceResponse.Hotel.Rooms.Room.Rates.Rate.CancellationPolicies.CancellationPolicy value) {
                                this.cancellationPolicy = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType&gt;
                             *   &lt;simpleContent&gt;
                             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                             *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
                             *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
                             *     &lt;/extension&gt;
                             *   &lt;/simpleContent&gt;
                             * &lt;/complexType&gt;
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "value"
                            })
                            public static class CancellationPolicy {

                                @XmlValue
                                protected String value;
                                @XmlAttribute(name = "amount")
                                protected BigDecimal amount;
                                @XmlAttribute(name = "from")
                                @XmlSchemaType(name = "dateTime")
                                protected XMLGregorianCalendar from;

                                /**
                                 * Gets the value of the value property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getValue() {
                                    return value;
                                }

                                /**
                                 * Sets the value of the value property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setValue(String value) {
                                    this.value = value;
                                }

                                /**
                                 * Gets the value of the amount property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link BigDecimal }
                                 *     
                                 */
                                public BigDecimal getAmount() {
                                    return amount;
                                }

                                /**
                                 * Sets the value of the amount property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link BigDecimal }
                                 *     
                                 */
                                public void setAmount(BigDecimal value) {
                                    this.amount = value;
                                }

                                /**
                                 * Gets the value of the from property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link XMLGregorianCalendar }
                                 *     
                                 */
                                public XMLGregorianCalendar getFrom() {
                                    return from;
                                }

                                /**
                                 * Sets the value of the from property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link XMLGregorianCalendar }
                                 *     
                                 */
                                public void setFrom(XMLGregorianCalendar value) {
                                    this.from = value;
                                }

                            }

                        }

                    }

                }

            }

        }

    }

}
