//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.04 at 02:30:19 PM IST 
//


package com.bonton.utility.artifacts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Source"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RequestorId"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="Client" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="Password" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="RequestorPreferences"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="RequestMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RequestDetails"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SearchHotelPriceRequest"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="ItemDestination" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="destinationCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="destinationType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="MinStarRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="MaxStarRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="ImmediateConfirmationOnly" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="PeriodOfStay"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="IncludeRecommended" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="IncludePriceBreakdown" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="IncludeChargeConditions" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Rooms"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Room" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="Occupant" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;simpleContent&gt;
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                                         &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="age" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                                         &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                         &lt;attribute name="surname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                       &lt;/extension&gt;
 *                                                     &lt;/simpleContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                               &lt;attribute name="noOfRooms" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                               &lt;attribute name="adults" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                               &lt;attribute name="children" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Hotels" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="Hotel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2000"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "source",
    "requestDetails"
})
@XmlRootElement(name = "BTNSearchRequest")
public class BTNSearchRequest {

    @XmlElement(name = "Source", required = true)
    protected BTNSearchRequest.Source source;
    @XmlElement(name = "RequestDetails", required = true)
    protected BTNSearchRequest.RequestDetails requestDetails;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link BTNSearchRequest.Source }
     *     
     */
    public BTNSearchRequest.Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link BTNSearchRequest.Source }
     *     
     */
    public void setSource(BTNSearchRequest.Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the requestDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BTNSearchRequest.RequestDetails }
     *     
     */
    public BTNSearchRequest.RequestDetails getRequestDetails() {
        return requestDetails;
    }

    /**
     * Sets the value of the requestDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BTNSearchRequest.RequestDetails }
     *     
     */
    public void setRequestDetails(BTNSearchRequest.RequestDetails value) {
        this.requestDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SearchHotelPriceRequest"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="ItemDestination" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="destinationCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="destinationType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="MinStarRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="MaxStarRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="ImmediateConfirmationOnly" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="PeriodOfStay"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                             &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="IncludeRecommended" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="IncludePriceBreakdown" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                   &lt;element name="IncludeChargeConditions" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Rooms"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Room" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="Occupant" maxOccurs="unbounded" minOccurs="0"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;simpleContent&gt;
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="age" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                               &lt;attribute name="surname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                             &lt;/extension&gt;
     *                                           &lt;/simpleContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                     &lt;attribute name="noOfRooms" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                                     &lt;attribute name="adults" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                                     &lt;attribute name="children" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Hotels" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="Hotel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2000"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "searchHotelPriceRequest"
    })
    public static class RequestDetails {

        @XmlElement(name = "SearchHotelPriceRequest", required = true)
        protected BTNSearchRequest.RequestDetails.SearchHotelPriceRequest searchHotelPriceRequest;

        /**
         * Gets the value of the searchHotelPriceRequest property.
         * 
         * @return
         *     possible object is
         *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest }
         *     
         */
        public BTNSearchRequest.RequestDetails.SearchHotelPriceRequest getSearchHotelPriceRequest() {
            return searchHotelPriceRequest;
        }

        /**
         * Sets the value of the searchHotelPriceRequest property.
         * 
         * @param value
         *     allowed object is
         *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest }
         *     
         */
        public void setSearchHotelPriceRequest(BTNSearchRequest.RequestDetails.SearchHotelPriceRequest value) {
            this.searchHotelPriceRequest = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="ItemDestination" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="destinationCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="destinationType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="MinStarRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="MaxStarRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="ImmediateConfirmationOnly" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="PeriodOfStay"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                   &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="IncludeRecommended" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="IncludePriceBreakdown" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *         &lt;element name="IncludeChargeConditions" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Rooms"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Room" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="Occupant" maxOccurs="unbounded" minOccurs="0"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;simpleContent&gt;
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="age" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                     &lt;attribute name="surname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                   &lt;/extension&gt;
         *                                 &lt;/simpleContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                           &lt;attribute name="noOfRooms" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                           &lt;attribute name="adults" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                           &lt;attribute name="children" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Hotels" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="Hotel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2000"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itemDestination",
            "minStarRating",
            "maxStarRating",
            "immediateConfirmationOnly",
            "periodOfStay",
            "includeRecommended",
            "includePriceBreakdown",
            "includeChargeConditions",
            "rooms",
            "hotels"
        })
        public static class SearchHotelPriceRequest {

            @XmlElement(name = "ItemDestination")
            protected BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.ItemDestination itemDestination;
            @XmlElement(name = "MinStarRating")
            protected String minStarRating;
            @XmlElement(name = "MaxStarRating")
            protected String maxStarRating;
            @XmlElement(name = "ImmediateConfirmationOnly", required = true)
            protected String immediateConfirmationOnly;
            @XmlElement(name = "PeriodOfStay", required = true)
            protected BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.PeriodOfStay periodOfStay;
            @XmlElement(name = "IncludeRecommended", required = true)
            protected String includeRecommended;
            @XmlElement(name = "IncludePriceBreakdown", defaultValue = "true")
            protected boolean includePriceBreakdown;
            @XmlElement(name = "IncludeChargeConditions", required = true)
            protected String includeChargeConditions;
            @XmlElement(name = "Rooms", required = true)
            protected BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms rooms;
            @XmlElement(name = "Hotels")
            protected BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Hotels hotels;

            /**
             * Gets the value of the itemDestination property.
             * 
             * @return
             *     possible object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.ItemDestination }
             *     
             */
            public BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.ItemDestination getItemDestination() {
                return itemDestination;
            }

            /**
             * Sets the value of the itemDestination property.
             * 
             * @param value
             *     allowed object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.ItemDestination }
             *     
             */
            public void setItemDestination(BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.ItemDestination value) {
                this.itemDestination = value;
            }

            /**
             * Gets the value of the minStarRating property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMinStarRating() {
                return minStarRating;
            }

            /**
             * Sets the value of the minStarRating property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMinStarRating(String value) {
                this.minStarRating = value;
            }

            /**
             * Gets the value of the maxStarRating property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxStarRating() {
                return maxStarRating;
            }

            /**
             * Sets the value of the maxStarRating property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxStarRating(String value) {
                this.maxStarRating = value;
            }

            /**
             * Gets the value of the immediateConfirmationOnly property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImmediateConfirmationOnly() {
                return immediateConfirmationOnly;
            }

            /**
             * Sets the value of the immediateConfirmationOnly property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImmediateConfirmationOnly(String value) {
                this.immediateConfirmationOnly = value;
            }

            /**
             * Gets the value of the periodOfStay property.
             * 
             * @return
             *     possible object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.PeriodOfStay }
             *     
             */
            public BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.PeriodOfStay getPeriodOfStay() {
                return periodOfStay;
            }

            /**
             * Sets the value of the periodOfStay property.
             * 
             * @param value
             *     allowed object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.PeriodOfStay }
             *     
             */
            public void setPeriodOfStay(BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.PeriodOfStay value) {
                this.periodOfStay = value;
            }

            /**
             * Gets the value of the includeRecommended property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIncludeRecommended() {
                return includeRecommended;
            }

            /**
             * Sets the value of the includeRecommended property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIncludeRecommended(String value) {
                this.includeRecommended = value;
            }

            /**
             * Gets the value of the includePriceBreakdown property.
             * 
             */
            public boolean isIncludePriceBreakdown() {
                return includePriceBreakdown;
            }

            /**
             * Sets the value of the includePriceBreakdown property.
             * 
             */
            public void setIncludePriceBreakdown(boolean value) {
                this.includePriceBreakdown = value;
            }

            /**
             * Gets the value of the includeChargeConditions property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIncludeChargeConditions() {
                return includeChargeConditions;
            }

            /**
             * Sets the value of the includeChargeConditions property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIncludeChargeConditions(String value) {
                this.includeChargeConditions = value;
            }

            /**
             * Gets the value of the rooms property.
             * 
             * @return
             *     possible object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms }
             *     
             */
            public BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms getRooms() {
                return rooms;
            }

            /**
             * Sets the value of the rooms property.
             * 
             * @param value
             *     allowed object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms }
             *     
             */
            public void setRooms(BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms value) {
                this.rooms = value;
            }

            /**
             * Gets the value of the hotels property.
             * 
             * @return
             *     possible object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Hotels }
             *     
             */
            public BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Hotels getHotels() {
                return hotels;
            }

            /**
             * Sets the value of the hotels property.
             * 
             * @param value
             *     allowed object is
             *     {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Hotels }
             *     
             */
            public void setHotels(BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Hotels value) {
                this.hotels = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Hotel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="2000"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "hotel"
            })
            public static class Hotels {

                @XmlElement(name = "Hotel", required = true)
                protected List<String> hotel;

                /**
                 * Gets the value of the hotel property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the hotel property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getHotel().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getHotel() {
                    if (hotel == null) {
                        hotel = new ArrayList<String>();
                    }
                    return this.hotel;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="destinationCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="destinationType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class ItemDestination {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "destinationCode", required = true)
                protected String destinationCode;
                @XmlAttribute(name = "destinationType")
                protected String destinationType;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the destinationCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDestinationCode() {
                    return destinationCode;
                }

                /**
                 * Sets the value of the destinationCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDestinationCode(String value) {
                    this.destinationCode = value;
                }

                /**
                 * Gets the value of the destinationType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDestinationType() {
                    return destinationType;
                }

                /**
                 * Sets the value of the destinationType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDestinationType(String value) {
                    this.destinationType = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="CheckOutDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;element name="CheckInDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "checkOutDate",
                "checkInDate"
            })
            public static class PeriodOfStay {

                @XmlElement(name = "CheckOutDate", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar checkOutDate;
                @XmlElement(name = "CheckInDate", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar checkInDate;

                /**
                 * Gets the value of the checkOutDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getCheckOutDate() {
                    return checkOutDate;
                }

                /**
                 * Sets the value of the checkOutDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setCheckOutDate(XMLGregorianCalendar value) {
                    this.checkOutDate = value;
                }

                /**
                 * Gets the value of the checkInDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getCheckInDate() {
                    return checkInDate;
                }

                /**
                 * Sets the value of the checkInDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setCheckInDate(XMLGregorianCalendar value) {
                    this.checkInDate = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Room" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="Occupant" maxOccurs="unbounded" minOccurs="0"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;simpleContent&gt;
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="age" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                           &lt;attribute name="surname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                         &lt;/extension&gt;
             *                       &lt;/simpleContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *                 &lt;attribute name="noOfRooms" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *                 &lt;attribute name="adults" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *                 &lt;attribute name="children" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "room"
            })
            public static class Rooms {

                @XmlElement(name = "Room", required = true)
                protected List<BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room> room;

                /**
                 * Gets the value of the room property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the room property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getRoom().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room }
                 * 
                 * 
                 */
                public List<BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room> getRoom() {
                    if (room == null) {
                        room = new ArrayList<BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room>();
                    }
                    return this.room;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="Occupant" maxOccurs="unbounded" minOccurs="0"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;simpleContent&gt;
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="age" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *                 &lt;attribute name="surname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *               &lt;/extension&gt;
                 *             &lt;/simpleContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *       &lt;attribute name="noOfRooms" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                 *       &lt;attribute name="adults" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                 *       &lt;attribute name="children" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "occupant"
                })
                public static class Room {

                    @XmlElement(name = "Occupant")
                    protected List<BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room.Occupant> occupant;
                    @XmlAttribute(name = "noOfRooms", required = true)
                    protected int noOfRooms;
                    @XmlAttribute(name = "adults", required = true)
                    protected int adults;
                    @XmlAttribute(name = "children", required = true)
                    protected int children;

                    /**
                     * Gets the value of the occupant property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the occupant property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getOccupant().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room.Occupant }
                     * 
                     * 
                     */
                    public List<BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room.Occupant> getOccupant() {
                        if (occupant == null) {
                            occupant = new ArrayList<BTNSearchRequest.RequestDetails.SearchHotelPriceRequest.Rooms.Room.Occupant>();
                        }
                        return this.occupant;
                    }

                    /**
                     * Gets the value of the noOfRooms property.
                     * 
                     */
                    public int getNoOfRooms() {
                        return noOfRooms;
                    }

                    /**
                     * Sets the value of the noOfRooms property.
                     * 
                     */
                    public void setNoOfRooms(int value) {
                        this.noOfRooms = value;
                    }

                    /**
                     * Gets the value of the adults property.
                     * 
                     */
                    public int getAdults() {
                        return adults;
                    }

                    /**
                     * Sets the value of the adults property.
                     * 
                     */
                    public void setAdults(int value) {
                        this.adults = value;
                    }

                    /**
                     * Gets the value of the children property.
                     * 
                     */
                    public int getChildren() {
                        return children;
                    }

                    /**
                     * Sets the value of the children property.
                     * 
                     */
                    public void setChildren(int value) {
                        this.children = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;simpleContent&gt;
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="age" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
                     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *       &lt;attribute name="surname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *     &lt;/extension&gt;
                     *   &lt;/simpleContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Occupant {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "type")
                        protected String type;
                        @XmlAttribute(name = "age", required = true)
                        protected int age;
                        @XmlAttribute(name = "name")
                        protected String name;
                        @XmlAttribute(name = "surname")
                        protected String surname;

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the type property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getType() {
                            return type;
                        }

                        /**
                         * Sets the value of the type property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setType(String value) {
                            this.type = value;
                        }

                        /**
                         * Gets the value of the age property.
                         * 
                         */
                        public int getAge() {
                            return age;
                        }

                        /**
                         * Sets the value of the age property.
                         * 
                         */
                        public void setAge(int value) {
                            this.age = value;
                        }

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the surname property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSurname() {
                            return surname;
                        }

                        /**
                         * Sets the value of the surname property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSurname(String value) {
                            this.surname = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RequestorId"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="Client" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="Password" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="RequestorPreferences"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="RequestMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestorId",
        "requestorPreferences"
    })
    public static class Source {

        @XmlElement(name = "RequestorId", required = true)
        protected BTNSearchRequest.Source.RequestorId requestorId;
        @XmlElement(name = "RequestorPreferences", required = true)
        protected BTNSearchRequest.Source.RequestorPreferences requestorPreferences;

        /**
         * Gets the value of the requestorId property.
         * 
         * @return
         *     possible object is
         *     {@link BTNSearchRequest.Source.RequestorId }
         *     
         */
        public BTNSearchRequest.Source.RequestorId getRequestorId() {
            return requestorId;
        }

        /**
         * Sets the value of the requestorId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BTNSearchRequest.Source.RequestorId }
         *     
         */
        public void setRequestorId(BTNSearchRequest.Source.RequestorId value) {
            this.requestorId = value;
        }

        /**
         * Gets the value of the requestorPreferences property.
         * 
         * @return
         *     possible object is
         *     {@link BTNSearchRequest.Source.RequestorPreferences }
         *     
         */
        public BTNSearchRequest.Source.RequestorPreferences getRequestorPreferences() {
            return requestorPreferences;
        }

        /**
         * Sets the value of the requestorPreferences property.
         * 
         * @param value
         *     allowed object is
         *     {@link BTNSearchRequest.Source.RequestorPreferences }
         *     
         */
        public void setRequestorPreferences(BTNSearchRequest.Source.RequestorPreferences value) {
            this.requestorPreferences = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="Client" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="Password" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class RequestorId {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Client")
            protected String client;
            @XmlAttribute(name = "EmailAddress")
            protected String emailAddress;
            @XmlAttribute(name = "Password")
            protected String password;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the client property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClient() {
                return client;
            }

            /**
             * Sets the value of the client property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClient(String value) {
                this.client = value;
            }

            /**
             * Gets the value of the emailAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmailAddress() {
                return emailAddress;
            }

            /**
             * Sets the value of the emailAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmailAddress(String value) {
                this.emailAddress = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="RequestMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "requestMode"
        })
        public static class RequestorPreferences {

            @XmlElement(name = "RequestMode", required = true)
            protected String requestMode;

            /**
             * Gets the value of the requestMode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequestMode() {
                return requestMode;
            }

            /**
             * Sets the value of the requestMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequestMode(String value) {
                this.requestMode = value;
            }

        }

    }

}
